### ISSUE TITLE
Title screen scaling is messed up

### ISSUE THREAD

**Issue by Tasosgemah** [GhostlyDark/MK64-HD#1]
This is how the title screen looks:

![Mario Kart 64 HD (USA)-231103-214132](https://github.com/GhostlyDark/MK64-HD/assets/12124465/eaba4ff9-0465-49d9-a9f6-4fa3cff04f90)

I followed the instructions for the correct core options. I tried to change some thing to fix this but nothing works. Using the latest mupen64plus_next core in RetroArch.

**Comment by Tasosgemah** [comment]
The best core options combination i could come up with is this:

[Mario Kart 64 HD (USA).txt](https://github.com/GhostlyDark/MK64-HD/files/13254172/Mario.Kart.64.HD.USA.txt)

This fixes the title screen and the character select screen but i still have that small glitch in the title screen:

![Mario Kart 64 HD (USA)-231103-220017](https://github.com/GhostlyDark/MK64-HD/assets/12124465/df10139b-1314-417b-9baa-5df054385c88)

You can see the blue lines under the text.

If i change anything else from that last .opt file i get a more broken title screen or character select screen. Can't find a combination that fixes everything. An older version of the pack using an older GlideN64 version was perfect.

**Comment by GhostlyDark** [comment]
Thank you for reporting.

Looks like one of my recent cleanups killed something I shouldn't have. The Push Start text is fixed via https://github.com/GhostlyDark/MK64-HD/commit/6840c2900a357d698e9af34c7c7e6cfafcf4d3d4.

By default, GLideN64 uses `texture coordinate bounds` to improve the visuals of the original textures, but HD textures in return generally suffer from this setting.

Additionally, the backgrounds show lines if the rendered resolution exceeds the upscale ratio of the HD textures. The backgrounds are 8x, so a `native resolution factor` of **8x and lower** fixes their appearance (320x240 -> 8x -> 2560x1920).
